name: Build and Test on Multiple Platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build on Linux and macOS
      if: runner.os != 'Windows'
      run: |
        gcc src/main.c -o hello_world
        echo "Build complete on ${{ matrix.os }}"

    - name: Build on Windows
      if: runner.os == 'Windows'
      run: |
        gcc src/main.c -o hello_world.exe
        echo "Build complete on ${{ matrix.os }}"

    - name: Test the build
      run: |
        ./hello_world || hello_world.exe

